import { CategoryInfo, Tool, ToolCategory } from "@/types/tools";

export const CATEGORIES: Record<ToolCategory, CategoryInfo> = {
  "encode-decode": {
    name: "Encode / Decode",
    icon: "Lock",
    description: "Encoding and decoding utilities",
  },
  formatters: {
    name: "Formatters",
    icon: "Code",
    description: "Code and data formatting tools",
  },
  generators: {
    name: "Generators",
    icon: "Sparkles",
    description: "Generate UUIDs, hashes, passwords and more",
  },
  converters: {
    name: "Converters",
    icon: "ArrowLeftRight",
    description: "Convert between different formats",
  },
  viewers: {
    name: "Viewers & Inspectors",
    icon: "Eye",
    description: "Inspect, test, and compare data",
  },
  ai: {
    name: "AI Powered",
    icon: "Brain",
    description: "AI-enhanced developer tools",
  },
};

export const TOOLS: Tool[] = [
  {
    slug: "base64",
    name: "Base64 Encode/Decode",
    description: "Encode and decode Base64 strings and files",
    category: "encode-decode",
    icon: "Binary",
    path: "/tools/encode-decode/base64",
    keywords: ["base64", "encode", "decode", "binary", "text"],
    priority: "P0",
  },
  {
    slug: "url",
    name: "URL Encode/Decode",
    description: "Encode and decode URL components",
    category: "encode-decode",
    icon: "Link2",
    path: "/tools/encode-decode/url",
    keywords: ["url", "encode", "decode", "query", "uri", "url-encode"],
    priority: "P0",
  },
  {
    slug: "jwt",
    name: "JWT Decoder",
    description: "Decode and inspect JSON Web Tokens",
    category: "encode-decode",
    icon: "KeyRound",
    path: "/tools/encode-decode/jwt",
    keywords: ["jwt", "token", "decode", "json", "auth", "jwt-decoder"],
    priority: "P0",
  },
  {
    slug: "html-entity",
    name: "HTML Entity Encode/Decode",
    description: "Encode and decode HTML entities",
    category: "encode-decode",
    icon: "FileCode",
    path: "/tools/encode-decode/html-entity",
    keywords: ["html", "entity", "encode", "decode", "escape"],
    priority: "P1",
  },
  {
    slug: "json",
    name: "JSON Formatter & Validator",
    description: "Format, minify, and validate JSON data",
    category: "formatters",
    icon: "Braces",
    path: "/tools/formatters/json",
    keywords: ["json", "format", "validator", "minify", "beautify", "json-formatter"],
    priority: "P0",
  },
  {
    slug: "sql",
    name: "SQL Formatter",
    description: "Format and beautify SQL queries",
    category: "formatters",
    icon: "Database",
    path: "/tools/formatters/sql",
    keywords: ["sql", "format", "query", "database", "beautify", "sql-formatter"],
    priority: "P1",
  },
  {
    slug: "markdown",
    name: "Markdown Preview",
    description: "Live Markdown editor with preview",
    category: "formatters",
    icon: "FileText",
    path: "/tools/formatters/markdown",
    keywords: ["markdown", "preview", "md", "editor", "format", "markdown-preview"],
    priority: "P0",
  },
  {
    slug: "code-formatter",
    name: "Code Formatter",
    description: "Format code in multiple languages",
    category: "formatters",
    icon: "Code2",
    path: "/tools/formatters/code-formatter",
    keywords: ["code", "formatter", "prettier", "beautify", "syntax"],
    priority: "P1",
  },
  {
    slug: "uuid",
    name: "UUID Generator",
    description: "Generate UUID v4 and v7 identifiers",
    category: "generators",
    icon: "Fingerprint",
    path: "/tools/generators/uuid",
    keywords: ["uuid", "v4", "v7", "guid", "generator", "uuid-generator"],
    priority: "P0",
  },
  {
    slug: "hash",
    name: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, SHA-512 hashes",
    category: "generators",
    icon: "Hash",
    path: "/tools/generators/hash",
    keywords: ["hash", "md5", "sha1", "sha256", "sha512", "hash-generator"],
    priority: "P0",
  },
  {
    slug: "password",
    name: "Password Generator",
    description: "Generate secure random passwords",
    category: "generators",
    icon: "Shield",
    path: "/tools/generators/password",
    keywords: ["password", "secure", "random", "generator", "security", "password-generator"],
    priority: "P1",
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text",
    category: "generators",
    icon: "TextCursorInput",
    path: "/tools/generators/lorem-ipsum",
    keywords: ["lorem", "ipsum", "text", "placeholder", "generator"],
    priority: "P2",
  },
  {
    slug: "timestamp",
    name: "Timestamp Converter",
    description: "Convert between Unix timestamps and dates",
    category: "converters",
    icon: "Clock",
    path: "/tools/converters/timestamp",
    keywords: ["timestamp", "unix", "date", "time", "converter", "timestamp-converter"],
    priority: "P0",
  },
  {
    slug: "color",
    name: "Color Converter",
    description: "Convert between HEX, RGB, HSL color formats",
    category: "converters",
    icon: "Palette",
    path: "/tools/converters/color",
    keywords: ["color", "hex", "rgb", "hsl", "converter", "color-converter"],
    priority: "P0",
  },
  {
    slug: "number-base",
    name: "Number Base Converter",
    description: "Convert between binary, octal, decimal, hex",
    category: "converters",
    icon: "Calculator",
    path: "/tools/converters/number-base",
    keywords: ["number", "base", "binary", "octal", "hex"],
    priority: "P1",
  },
  {
    slug: "unit-converter",
    name: "CSS Unit Converter",
    description: "Convert between px, rem, em, vw units",
    category: "converters",
    icon: "Ruler",
    path: "/tools/converters/unit-converter",
    keywords: ["css", "unit", "px", "rem", "em"],
    priority: "P2",
  },
  {
    slug: "regex",
    name: "Regex Tester",
    description: "Test regular expressions with real-time matching",
    category: "viewers",
    icon: "Regex",
    path: "/tools/viewers/regex",
    keywords: ["regex", "regexp", "tester", "pattern", "match", "regex-tester"],
    priority: "P0",
  },
  {
    slug: "diff",
    name: "Diff Viewer",
    description: "Compare text and code side by side",
    category: "viewers",
    icon: "GitCompare",
    path: "/tools/viewers/diff",
    keywords: ["diff", "compare", "text", "code", "patch", "diff-viewer"],
    priority: "P0",
  },
  {
    slug: "http-status",
    name: "HTTP Status Codes",
    description: "Reference for all HTTP status codes",
    category: "viewers",
    icon: "Globe",
    path: "/tools/viewers/http-status",
    keywords: ["http", "status", "codes", "api", "reference"],
    priority: "P1",
  },
  {
    slug: "cron",
    name: "Cron Expression Parser",
    description: "Parse and explain cron expressions",
    category: "viewers",
    icon: "CalendarClock",
    path: "/tools/viewers/cron",
    keywords: ["cron", "parser", "schedule", "expression", "timer", "cron-parser"],
    priority: "P1",
  },
  {
    slug: "ai-code-explain",
    name: "AI Code Explainer",
    description: "AI explains your code logic",
    category: "ai",
    icon: "Bot",
    path: "/tools/ai/ai-code-explain",
    keywords: ["ai", "code", "explain", "assistant", "review"],
    isAI: true,
    priority: "P1",
  },
  {
    slug: "ai-code-convert",
    name: "AI Code Converter",
    description: "Convert code between programming languages",
    category: "ai",
    icon: "RefreshCw",
    path: "/tools/ai/ai-code-convert",
    keywords: ["ai", "code", "convert", "translate", "language"],
    isAI: true,
    priority: "P1",
  },
  {
    slug: "ai-regex-gen",
    name: "AI Regex Generator",
    description: "Generate regex from natural language",
    category: "ai",
    icon: "Brain",
    path: "/tools/ai/ai-regex-gen",
    keywords: ["ai", "regex", "generate", "pattern", "nlp"],
    isAI: true,
    priority: "P1",
  },
];

export function getToolsByCategory(category: ToolCategory): Tool[] {
  return TOOLS.filter((t) => t.category === category);
}

export function getToolBySlug(slug: string): Tool | undefined {
  const legacyMap: Record<string, string> = {
    "url-encode": "url",
    "jwt-decoder": "jwt",
    "json-formatter": "json",
    "markdown-preview": "markdown",
    "uuid-generator": "uuid",
    "hash-generator": "hash",
    "timestamp-converter": "timestamp",
    "color-converter": "color",
    "regex-tester": "regex",
    "diff-viewer": "diff",
    "sql-formatter": "sql",
    "password-generator": "password",
    "cron-parser": "cron",
  };
  const normalizedSlug = legacyMap[slug] ?? slug;
  return TOOLS.find((t) => t.slug === normalizedSlug);
}

export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase();
  return TOOLS.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.keywords.some((k) => k.includes(q))
  );
}
